#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mete Balci
# SPDX-License-Identifier: AGPL-3.0-or-later
# Extract data/BUSINT.netlist from MIT's SUDS drawings of the bus interface.
#
# The drawings are MIT's own `mit/cadr1/*.drw`; the reader is tools/soap4,
# this project's copy of `ams/cadr4`'s `soap4`, which emits the 2004 netlist
# format that src/netlist.rs reads.  Everything it reads is in this
# repository.
#
# usage: tools/busint-netlist.sh

set -eu

muir=$(cd "$(dirname "$0")/.." && pwd)
mit=$muir/mit
build=$muir/vendor/soap
bodies=$mit/cadr/bodies.drw

[ -d "$mit/cadr1" ] || { echo "no cadr1 drawings in $mit" >&2; exit 1; }

mkdir -p "$build"
cc -O2 -w -o "$build/soap4" "$muir/tools/soap4/soap4.c" "$muir/tools/soap4/unpack4.c"

# The pages are MIT's own, not the directory: `cadr1/busint.book` is the
# board's print set and names these 35, in this order once sorted. The rest
# of `cadr1/` is a second board --- the nine `cdc*` pages of the CDC adaptor,
# which `cadr1/cdc.fil` lists and `busint.wls` does not count --- and three
# sheets that carry no parts: `blank`, `init` and `memd1`. Globbing the
# directory took the CDC adaptor's 18 parts as the bus interface's on any
# reader that can read those pages.
pages="buspar bussel caps clm ctp cubus cxbus datctl dbgin dbgout diag dpadr
       dpdata lmadr lmdata rbuf reqerr reqlm reqtim requ requb rqsync uba
       ubcyc ubd ubintc ubmap ubmast ubxa uprior wbuf xa xapar xbd xd"

# One `page` block per drawing, under one banner.
generate() {
    printf '#\n# generated by tools/busint-netlist.sh, using ams/cadr4 soap4\n#\n\n'
    for p in $pages; do
        # Every one of the 35 pages reads: CI regenerates this netlist and
        # diffs it against the committed one, so a page soap4 cannot read is
        # a real fault and not a known gap. Stop rather than write a netlist
        # quietly missing a board's worth of parts.
        "$build/soap4" -e "$bodies" -o netlist -x cadr "$1/$p.drw" || {
            echo "cannot read $p.drw" >&2
            exit 1
        }
    done
}

# MIT's own wire list for the board, cadr1/busint.wlr, settles what
# soap4 gets wrong: a wire the drawings label twice comes out as two nets,
# a name spelt with and without a space as two, and six pins are lost to
# `@,p0`. examples/reconcile.rs puts each such wire on one net under MIT's
# name, and tests/busint_netlist.rs checks the result against the list.
#
# The same step corrects the one pin the drawing itself has wrong: REQLM
# E09 pin 2, the grant that gates a Unibus master's Xbus request, which the
# 10-DEC-80 reqlm.drw has on LMX GRANT A and its 3-OCT-78 revision on UBX
# GRANT A (discrepancy 68). The 1980 drawing stays the source;
# examples/reconcile.rs's MOVES table moves that pin, refuses a drawing
# that no longer has the error, and writes what it did into the banner of
# data/BUSINT.netlist.
generate "$mit/cadr1" > "$build/BUSINT.raw.netlist"
(cd "$muir" && cargo run --release --quiet --example reconcile -- \
    "$build/BUSINT.raw.netlist" "$mit/cadr1/busint.wlr" 0) \
    > "$muir/data/BUSINT.netlist"
echo "wrote data/BUSINT.netlist: \
$(grep -c '^page ' "$muir/data/BUSINT.netlist") pages, \
$(grep -c '^part ' "$muir/data/BUSINT.netlist") parts"
