#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mete Balci
# SPDX-License-Identifier: AGPL-3.0-or-later
# Extract data/CADRIO.netlist from MIT's SUDS drawings of the I/O board.
#
# The drawings are all twenty-seven pages `cadrio/iob.stf` and
# `cadrio/iob.wlr` list for this board: the fourteen `cadrio/*.drw` pages
# of the I/O half, and the thirteen `chaos/lm*.drw` pages of the Chaosnet
# half, which shares the board and lives in `chaos/lispm/`.  `chaos/` on
# the tapes holds four other machines' interfaces --- the CONS's, the
# PDP-10's, the CAIOS network's and a Q-bus board's --- under confusingly
# similar page names, which is
# why they are in folders of their own and why these pages are named and
# not globbed.  All thirteen read with the I/O board's own body library.
#
# More than one copy of eleven of the thirteen is on the tapes, the dumps
# having lost their ITS dates; built from the wrong ones this board disagrees
# with MIT's own wire list in 39 places and seven pages need a second body
# library to read at all.  The copies in `mit/chaos/lispm/` are this board's,
# filed apart from the CONS, CAIOS and PDP-10 versions of the same sheets.
# The reader is tools/soap4, built as
# tools/busint-netlist.sh builds it, with the I/O board's own body
# library, `cadrio/bodies.drw`. `hexspc` and `iobjps` (spare gates,
# jumpers) carry no reference designators and read as nothing; `clk60h`
# has a control character in a net name, which the reader drops. soap4 names a net the drawing leaves unnamed `net_NN` per page, so
# each is suffixed with its page before the pages are joined.
#
# Then MIT's own wire list for the board, cadrio/iob.wlr (11 August 1981),
# settles what soap4 gets wrong, as it did for the bus interface:
# examples/reconcile.rs puts each wire the drawings label twice on one net
# under MIT's name, and tests/cadrio_netlist.rs checks the result against
# the list.
#
# usage: tools/cadrio-netlist.sh
set -eu
muir=$(cd "$(dirname "$0")/.." && pwd)
mit=$muir/mit
build=$muir/vendor/soap
bodies=$mit/cadrio/bodies.drw
[ -d "$mit/cadrio" ] || { echo "no cadrio drawings in $mit" >&2; exit 1; }
mkdir -p "$build"
cc -O2 -w -o "$build/soap4" "$muir/tools/soap4/soap4.c" "$muir/tools/soap4/unpack4.c"
pages="clk60h clktim clktod hexspc iobadr iobclk iobcsr iobint iobjps iobkbd
       iobms2 iobmse iobser iobxcv"
chaos_pages="lmdatp lmdetc lmlndr lmmodu lmmynm lmrbuf lmrclk lmrctl lmtbfc
             lmtbuf lmtclk lmturn lmucon"

{
    printf '#\n# generated by tools/cadrio-netlist.sh, using ams/cadr4 soap4 and cadrio/bodies.drw\n#\n\n'
    for p in $pages; do
        page=$(echo "$p" | tr '[:lower:]' '[:upper:]')
        "$build/soap4" -e "$bodies" -o netlist -x cadr "$mit/cadrio/$p.drw" > "$build/page.raw" || {
            echo "cannot read $p.drw" >&2
            exit 1
        }
        sed "s/^\(p[0-9]*=net_[0-9]*\)\$/\1@$page/" "$build/page.raw"
    done
    for p in $chaos_pages; do
        page=$(echo "$p" | tr '[:lower:]' '[:upper:]')
        "$build/soap4" -e "$bodies" -o netlist -x cadr \
            "$mit/chaos/lispm/$p.drw" > "$build/page.raw" || {
            echo "cannot read $p.drw" >&2
            exit 1
        }
        sed "s/^\(p[0-9]*=net_[0-9]*\)\$/\1@$page/" "$build/page.raw"
    done
} > "$build/CADRIO.raw.netlist"
(cd "$muir" && cargo run --release --quiet --example reconcile -- \
    "$build/CADRIO.raw.netlist" "$mit/cadrio/iob.wlr" 0) \
    > "$muir/data/CADRIO.netlist"
echo "wrote data/CADRIO.netlist: \
$(grep -c '^page ' "$muir/data/CADRIO.netlist") pages, \
$(grep -c '^part ' "$muir/data/CADRIO.netlist") parts"
