#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mete Balci
# SPDX-License-Identifier: AGPL-3.0-or-later
# Extract data/CADRM.netlist from MIT's SUDS drawings of the memory board.
#
# The drawings are `cadrm/*.drw`, the 64K-word board of four banks of 4116
# DRAMs; the reader is tools/soap4, built as tools/busint-netlist.sh
# builds it. Two things differ from the bus interface:
#
# - The bodies library is the I/O board's, `cadrio/bodies.drw`: the
#   processor's lacks `DIPOSC`, `74LS569`, `25LS2539` and `S00L`, which four
#   of the memory pages use, and on every page both libraries can read they
#   produce the same netlist, which is checked.
# - The pages are named, not globbed. `cadrm/` also holds six `pm*.drw`
#   whose parts carry no location designators and read as nothing, and
#   eight `mcp*.drw` of bypass capacitors; the fifteen below are the board.
#
# soap4 names a net the drawing leaves unnamed `net_NN`, numbering from zero
# on every page, so the same name means different wires on different pages;
# each is suffixed with its page here, as `net_NN@MEMCTL`, before the pages
# are joined.
#
# MIT's wire list for the board, `cadrm/mem.wlr` (4 March 1980), is the
# second copy: `tests/cadrm_netlist.rs` holds the netlist to it, with ECO 2
# of `cadrm/mem.eco` applied to the list, since the drawings are after it.
#
# usage: tools/cadrm-netlist.sh
set -eu
muir=$(cd "$(dirname "$0")/.." && pwd)
mit=$muir/mit
build=$muir/vendor/soap
bodies=$mit/cadrio/bodies.drw
[ -d "$mit/cadrm" ] || { echo "no cadrm drawings in $mit" >&2; exit 1; }
mkdir -p "$build"
cc -O2 -w -o "$build/soap4" "$muir/tools/soap4/soap4.c" "$muir/tools/soap4/unpack4.c"
pages="mem0lh mem0rh mem1lh mem1rh mem2lh mem2rh mem3lh mem3rh
       memadl memadr memads memctl memras memxba memxbd"
{
    printf '#\n# generated by tools/cadrm-netlist.sh, using ams/cadr4 soap4 and cadrio/bodies.drw\n#\n\n'
    for p in $pages; do
        page=$(echo "$p" | tr '[:lower:]' '[:upper:]')
        "$build/soap4" -e "$bodies" -o netlist -x cadr "$mit/cadrm/$p.drw" > "$build/page.raw" || {
            echo "cannot read $p.drw" >&2
            exit 1
        }
        sed "s/^\(p[0-9]*=net_[0-9]*\)\$/\1@$page/" "$build/page.raw"
    done
} > "$muir/data/CADRM.netlist"
echo "wrote data/CADRM.netlist: \
$(grep -c '^page ' "$muir/data/CADRM.netlist") pages, \
$(grep -c '^part ' "$muir/data/CADRM.netlist") parts"
