#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mete Balci
# SPDX-License-Identifier: AGPL-3.0-or-later
# Extract data/CADR.netlist from MIT's SUDS drawings of the CADR processor.
#
# The processor is two boards, and MIT calls each a *section* of it: the
# CADR section, whose print set is `cadr/cadr.book`, and the ICMEM section,
# whose print set is `cadr/icmem.book`. Both sections go in one netlist,
# because the cables join them and `tests/netlist.rs` checks that join pin
# for pin against the two wire lists.
#
# The pages are MIT's own, not the directory: the two `.book` files name 64
# and 33, and `cadr/` holds 126 drawings. The two lists together are exactly
# the 97 pages of the file this replaces --- `uhdl`'s `CADR4.netlist`, made
# from the same drawings in 2004 by Brad Parker's `soap.c` --- with no page
# in one and not the other, which is the first check on the page list.
#
# soap4 refuses a drawing whose points carry bits it does not know, and
# `CPINS` is one: `unexpected point bits #o001000`. Its `page` marker is
# written anyway, with no parts under it, and no part is lost by that: the
# drawing is connector connections only, a
# signal entering a connector symbol. `cadrwd/cadr4.stf` stuffs nothing on
# the page and every `CPINS` line of `cadrwd/cadr4.wlr` but the header is a
# `CON`. The marker has to be there for the wire list to place those
# connector pins on a page --- which is what `tests/netlist.rs` joins the
# two boards by.
#
# **Two second copies, and they are MIT's own.** `cadrwd/cadr4.wlr` and
# `cadrwd/icmem3.wlr` are the wire lists the two boards were wrapped from,
# one per board. They settle what the reader gets wrong, as they do for
# every other board here: a wire the drawings label twice comes out as two
# nets, and `examples/reconcile.rs` puts every pin of such a wire on one net
# under MIT's name. `tests/netlist.rs` then holds the result to both lists.
#
# usage: tools/cadr-netlist.sh
set -eu
muir=$(cd "$(dirname "$0")/.." && pwd)
mit=$muir/mit
build=$muir/vendor/soap
drw=$mit/cadr
bodies=$drw/bodies.drw
wd=$mit/cadrwd

[ -d "$drw" ] || { echo "no cadr drawings in $mit" >&2; exit 1; }

mkdir -p "$build"
cc -O2 -w -o "$build/soap4" "$muir/tools/soap4/soap4.c" "$muir/tools/soap4/unpack4.c"

# The page names out of MIT's print sets, in the order the sets list them:
# every quoted string, less the `AI:CADR;` the first one carries.
pages_of() {
    awk -v RS='"' 'NR%2==0' "$1" | sed 's|^AI:CADR;||' | grep -E '^[A-Z0-9]+$'
}

{
    printf '#\n# generated by tools/cadr-netlist.sh, using tools/soap4\n'
    printf '# the CADR processor: cadr.book and icmem.book, both sections\n#\n\n'
    for page in $(pages_of "$drw/cadr.book") $(pages_of "$drw/icmem.book"); do
        p=$(echo "$page" | tr '[:upper:]' '[:lower:]')
        "$build/soap4" -e "$bodies" -o netlist -x cadr "$drw/$p.drw" || {
            echo "cannot read $p.drw: writing the page marker alone" >&2
            printf 'page %s\n\n' "$page"
        }
    done
} > "$build/CADR.raw.netlist"

# Each board against its own wire list, in turn: the CADR section's slots
# are the netlist's designators unprefixed, and so are the ICMEM section's.
(cd "$muir" && cargo run --release --quiet --example reconcile -- \
    "$build/CADR.raw.netlist" "$wd/cadr4.wlr" '') > "$build/CADR.half.netlist"
(cd "$muir" && cargo run --release --quiet --example reconcile -- \
    "$build/CADR.half.netlist" "$wd/icmem3.wlr" '') > "$muir/data/CADR.netlist"

echo "wrote data/CADR.netlist: \
$(grep -c '^page ' "$muir/data/CADR.netlist") pages, \
$(grep -c '^part ' "$muir/data/CADR.netlist") parts"
