#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mete Balci
# SPDX-License-Identifier: AGPL-3.0-or-later
# Extract data/CADRDC.netlist from MIT's SUDS drawings of the disk controller.
#
# The board is the DISK CONTROL, the Xbus device `src/disk_controller.rs`
# models: a command list at `17377774`, a Trident T-300 on the other side of
# it, and the microcoded sequencer between. `cadrdc/` holds three boards ---
# DISK CONTROL, DISK MULTIPLEXOR (`dm*`) and MARKSMAN CONTROL (`mk*`) --- and
# the pages below are the 27 that `cadrdc/dc.book`, MIT's own print set for
# this one, names, in the order it names them. `dc.wls` and `dc.stf` name the
# same 27, and every one of them has a readable drawing.
#
# **Which body library.** The drawing's own header names it. All but two say
# `CADRIO;BODIES DRW`, which is the library the memory and I/O boards use;
# `dcedge` and `xbus`, the two connector pages, name none; and `dctrsg` names
# two, `CADR;SIPS DRW` for its `SIP100-8` cable terminators and
# `CADRIO;BODIES DRW` for the rest, which is why soap4's `-e` had to become
# repeatable. That fix went back to `ams/cadr4`; tools/soap4 has it from there.
#
# **Two second copies.** `cadrdc/dc.wlr` (10 December 1980) is the wire list
# the board was wrapped from, and `cadrdc/dc.wls` the section census MIT's
# tooling made of the drawings the same day. As for the bus interface and the
# I/O board, the wire list settles what soap4 gets wrong: a wire the drawings
# label twice comes out as two nets, and `examples/reconcile.rs` puts each
# such wire on one net under MIT's name. `tests/cadrdc_netlist.rs` then holds
# the result to both files.
#
# soap4 names a net the drawing leaves unnamed `net_NN`, numbering from zero
# on every page, so each is suffixed with its page here before the pages are
# joined, as `tools/cadrm-netlist.sh` does.
#
# usage: tools/cadrdc-netlist.sh
set -eu
muir=$(cd "$(dirname "$0")/.." && pwd)
mit=$muir/mit
build=$muir/vendor/soap
drw=$mit/cadrdc
bodies=$mit/cadrio/bodies.drw
sips=$mit/cadr/sips.drw
[ -d "$drw" ] || { echo "no cadrdc drawings in $mit" >&2; exit 1; }
mkdir -p "$build"
cc -O2 -w -o "$build/soap4" "$muir/tools/soap4/soap4.c" "$muir/tools/soap4/unpack4.c"

# `cadrdc/` also holds `dcud.drw`, DISK CONTROL / MICRO PROGRAM COUNTER of 24
# February 1978, which none of MIT's three lists for this board names --- not
# `dc.book`, not `dc.wls`, not `dc.stf`, all three of 10 December 1980. It is
# a superseded sheet and is not taken.
pages="dcbusy dccaps dcccw dcchan dcclk dcclp dccmd dcda dcdbus dcecc dcedge
       dchdcm dcpar dcposc dcrbuf dcreg dcsh dcsts dctmot dctrid dctrsg dcuc
       dcui dcwbuf dcxbsa dcxbus xbus"

{
    printf '#\n# generated by tools/cadrdc-netlist.sh, using ams/cadr4 soap4\n'
    printf '# and the body libraries the drawings name, cadrio/bodies.drw and\n'
    printf '# cadr/sips.drw\n#\n\n'
    for p in $pages; do
        page=$(echo "$p" | tr '[:lower:]' '[:upper:]')
        "$build/soap4" -e "$sips" -e "$bodies" -o netlist -x cadr "$drw/$p.drw" > "$build/page.raw" || {
            echo "cannot read $p.drw" >&2
            exit 1
        }
        sed "s/^\(p[0-9]*=net_[0-9]*\)\$/\1@$page/" "$build/page.raw"
    done
} > "$build/CADRDC.raw.netlist"
(cd "$muir" && cargo run --release --quiet --example reconcile -- \
    "$build/CADRDC.raw.netlist" "$drw/dc.wlr" 0) \
    > "$muir/data/CADRDC.netlist"
echo "wrote data/CADRDC.netlist: \
$(grep -c '^page ' "$muir/data/CADRDC.netlist") pages, \
$(grep -c '^part ' "$muir/data/CADRDC.netlist") parts"
