#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mete Balci
# SPDX-License-Identifier: AGPL-3.0-or-later
# Extract data/DM.netlist from MIT's SUDS drawings of the disk multiplexor.
#
# The board is the DISK MULTIPLEXOR, which sits between one disk controller
# and up to eight Trident drives. `cadrdc/` holds three boards --- DISK
# CONTROL (`dc*`), this one (`dm*`) and MARKSMAN CONTROL (`mk*`) --- and the
# eleven pages below are the eleven that `cadrdc/dm.txt`, MIT's own page
# list for this board, names, in the order it names them. `dm.fil` and
# `dm.stf` name the same eleven.
#
# **`dm.wls` names ten of them and is not a census.** Every other board's
# `.wls` carries MIT's section census --- the "DIPTYPE / BODY NAME / #
# SECTION" table `tests/*_netlist.rs` hold an extraction to --- and this one
# does not: it is a page list and stops there, 51 lines against `dc.wls`'s
# 466. It also leaves `DMSEQ` out, where `dm.txt`, `dm.fil` and `dm.stf` all
# have it and the drawing itself carries 23 sections. It is dated 15
# December 1979 against `dc.wls`'s 10 December 1980, and its pages are dated
# March 1979: an earlier snapshot. Discrepancy 75.
#
# **Which body library. The drawing's own header names it**, as it does on
# the board beside this one, and the pattern is the same: nine pages say
# `CADRIO;BODIES DRW`; `dmio` says `CADR;SIPS DRW` *and* `CADRIO;BODIES
# DRW`, exactly as `dctrsg` does on the controller, which is why soap4's
# `-e` is repeatable; and the two connector pages, `dmcabl` and `dmedge`,
# name none, as `dcedge` and `xbus` name none. The name is sixbit in the
# header, so `strings` does not show it; `soap4 -d` prints it as "library
# filespec".
#
# Given only `cadrio/bodies.drw`, `dmio` dies on `assert(0)` in
# `assign_same_ids_of_points` --- which looks like an unreadable drawing
# and is not. It is worth knowing which way round that goes: on the
# Chaosnet pages a page that wanted a library its header did not name was
# the symptom of a **wrong copy**, and here the header names it, so this
# is MIT's own authority for the second library and not a trial that
# happened to work.
#
# **`dmcabl` needed soap4 taught one point encoding**, `#o001000`, CPIN with
# no text and nothing else; `tools/soap4/soap4.c` carries the entry and it
# should go back to ams/cadr4 as the earlier fixes did. It reads cleanly
# now and yields no bodies and no points, which is what every connector page
# yields here: `dcedge` and `xbus` do the same in `data/CADRDC.netlist`. The
# board's cable and edge connections are therefore **not** in this file.
#
# **No wire list.** MIT left none of this board --- `dc.wlr` and `mk.wlr`
# exist, `dm.wlr` does not --- so `examples/reconcile.rs` runs with `-`, as
# it does for the SIMPLE TV, and makes no move. Nothing joins a net the
# drawings label twice back together here, where every board with a `.wlr`
# has that done for it; `tests/dm_netlist.rs` reports how many nets carry a
# name another net also carries.
#
# soap4 names a net the drawing leaves unnamed `net_NN`, numbering from zero
# on every page, so each is suffixed with its page here before the pages are
# joined, as `tools/cadrdc-netlist.sh` does.
#
# usage: tools/dm-netlist.sh
set -eu
muir=$(cd "$(dirname "$0")/.." && pwd)
mit=$muir/mit
build=$muir/vendor/soap
drw=$mit/cadrdc
bodies=$mit/cadrio/bodies.drw
sips=$mit/cadr/sips.drw
[ -d "$drw" ] || { echo "no cadrdc drawings in $mit" >&2; exit 1; }
mkdir -p "$build"
cc -O2 -w -o "$build/soap4" "$muir/tools/soap4/soap4.c" "$muir/tools/soap4/unpack4.c"

pages="dmbkc0 dmbkc1 dmcabl dmcaps dmedge dmio dmmux dmrdwr dmsect dmsel dmseq"

{
    printf '#\n# generated by tools/dm-netlist.sh, using ams/cadr4 soap4 and the\n'
    printf '# body libraries cadrio/bodies.drw and cadr/sips.drw\n#\n\n'
    for p in $pages; do
        page=$(echo "$p" | tr '[:lower:]' '[:upper:]')
        "$build/soap4" -e "$sips" -e "$bodies" -o netlist -x cadr "$drw/$p.drw" > "$build/page.raw" || {
            echo "cannot read $p.drw" >&2
            exit 1
        }
        sed "s/^\(p[0-9]*=net_[0-9]*\)\$/\1@$page/" "$build/page.raw"
    done
} > "$build/DM.raw.netlist"
(cd "$muir" && cargo run --release --quiet --example reconcile -- \
    "$build/DM.raw.netlist" - 0) \
    > "$muir/data/DM.netlist"
echo "wrote data/DM.netlist: \
$(grep -c '^page ' "$muir/data/DM.netlist") pages, \
$(grep -c '^part ' "$muir/data/DM.netlist") parts"
