#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mete Balci
# SPDX-License-Identifier: AGPL-3.0-or-later
# Extract data/LISPMTV.netlist from MIT's SUDS drawings of the LISPM TV.
#
# The board is the LISPM TV, the four- and eight-bit display that replaced
# the SIMPLE TV in December 1980 --- `cadrtv/lmtv4b.fil` is its page list,
# 25 drawings, and `lmtv4b.stf` titles every one of them `LISPM TV`. It
# lives in `cadrtv/lispm-tv/`, sorted there by `ams/cadr4` by title block
# because six of its pages share filenames with the SIMPLE TV's
# (discrepancy 35). **Never glob `cadrtv/`.**
#
# Unlike the SIMPLE TV this board has MIT's wire list, `lmtv4b.wlr` of 7
# December 1980, so it is held to MIT's wiring the way the memory board and
# the disk controller are: `examples/reconcile.rs` puts each wire the
# drawings label twice on one net under the list's name, and
# `tests/lispmtv_netlist.rs` checks the result against the list and against
# `lmtv4b.wls`, the section census.
#
# Which body library each page takes is what its own header names: `bod2`
# for the TTL pages and `eclbod` for the three MECL ones.
#
# usage: tools/lispmtv-netlist.sh
set -eu
muir=$(cd "$(dirname "$0")/.." && pwd)
mit=$muir/mit
build=$muir/vendor/soap
drw=$mit/cadrtv
[ -d "$drw/lispm-tv" ] || { echo "no cadrtv drawings in $mit" >&2; exit 1; }
mkdir -p "$build"
cc -O2 -w -o "$build/soap4" "$muir/tools/soap4/soap4.c" "$muir/tools/soap4/unpack4.c"

# lmtv4b.fil's 25 pages, in its order; the MECL three take eclbod.
ttl_pages="gen4b caps color rama ramb ramc ramd ramadr rambuf ramcas ramreg
           ramshf synadr synclk synram synreg tvma tvinc xbadr xbctl xbdata
           xbus"
ecl_pages="eclclk eclsip eclvid"

emit() {
    library=$1
    shift
    for p in "$@"; do
        page=$(echo "$p" | tr '[:lower:]' '[:upper:]')
        "$build/soap4" -e "$drw/$library.drw" -o netlist -x cadr "$drw/lispm-tv/$p.drw" > "$build/page.raw" || {
            echo "cannot read $p.drw" >&2
            exit 1
        }
        sed "s/^\(p[0-9]*=net_[0-9]*\)\$/\1@$page/" "$build/page.raw"
    done
}

{
    printf '#\n# generated by tools/lispmtv-netlist.sh, using ams/cadr4 soap4\n'
    printf '# and the body libraries the drawings name, cadrtv/bod2.drw and\n'
    printf '# cadrtv/eclbod.drw\n#\n\n'
    emit bod2 $ttl_pages
    emit eclbod $ecl_pages
} > "$build/LISPMTV.raw.netlist"
(cd "$muir" && cargo run --release --quiet --example reconcile -- \
    "$build/LISPMTV.raw.netlist" "$drw/lmtv4b.wlr" 0) \
    > "$muir/data/LISPMTV.netlist"
echo "wrote data/LISPMTV.netlist: \
$(grep -c '^page ' "$muir/data/LISPMTV.netlist") pages, \
$(grep -c '^part ' "$muir/data/LISPMTV.netlist") parts"
