#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mete Balci
# SPDX-License-Identifier: AGPL-3.0-or-later
# Extract data/SIMPLETV.netlist from MIT's SUDS drawings of the display board.
#
# The board is the SIMPLE TV, the black-and-white display `src/simpletv.rs` models
# --- `'(:VIDEO :BLACK-AND-WHITE :CONTROLLER :SIMPLE)'` to the window system,
# the "normal TV" of `cadrtv/lmtv.order`, control at `17377760` and buffer at
# `17000000`. It is not the LISPM TV, the four- and eight-bit board of
# `lmtv4b.fil` and `lmtv8b.fil` that replaced it in December 1980.
#
# **`cadrtv/` is two boards, kept apart by directory.** The SIMPLE TV was
# replaced in December 1980 by the LISPM TV, whose sheets took the filenames
# the SIMPLE TV's had used --- `ramcas`, `tvma`, `xbadr`, `xbdata` and the
# rest --- so under one flat directory the two boards collide, and a
# newest-copy-wins install kept the LISPM TV's sheet under each such name and
# lost the SIMPLE TV's (discrepancy 35). `ams/cadr4` now sorts
# every drawing into `simple-tv/` or `lispm-tv/` by its own title block, so
# the pages below are read from `simple-tv/` and nowhere else. **Never glob
# `cadrtv/`**: `lispm-tv/` holds files of the same six names.
#
# **Which sheets are the board.** MIT's own page list is `cadrtv/lmtv.stf`,
# `MARRTV;LMTV STF` of 28 May 1979: 29 drawings, every title `SIMPLE TV`. The
# board was revised once more after that list, on 24 January and 17 May 1980,
# and in that revision MIT renamed most of its pages with an `n` in front ---
# `ramadr` became `nraadr`, `synreg` `nsyreg` --- and folded `synmod` and
# `xbctl`, the mode register and the Xbus control, into one sheet, `nxbctl`.
# (The LISPM TV, seven months later, took the names that renaming had
# vacated; it did not cause it.) Six pages were never renamed and keep their
# 1979 names: `eclvid`, `ramcas`, `ramreg`, `tvma`, `xbadr` and `xbdata`.
# So the list below is `lmtv.stf`'s 29 carried forward to the May 1980
# revision --- 28 sheets, `synmod` and `xbctl` being one --- plus `rampwr`,
# the VDD and VBB wiring of 17 May 1980, which post-dates the list and
# carries no parts. `simple-tv/` also holds `synmod`, `ramcol` and `tvminc`,
# the 1978-79 sheets that `nxbctl`, `nracol` and `ntvinc` superseded; they
# are not taken. `tests/simpletv_netlist.rs` checks every banner says SIMPLE
# TV and that the page count is `lmtv.stf`'s.
#
# **Which body library.** The drawing's own header names it, in three SIXBIT
# words --- `SIMPLETV;BOD2 DRW` for the TTL pages, `SIMPLETV;ECLBOD DRW` for the
# MECL ones --- which is why soap4 had to be taught to read that header. That
# fix went back to `ams/cadr4`; tools/soap4 has it from there. Given the wrong
# library soap4 stops on the first body
# it cannot find, so a page that reads at all read with the right one.
#
# soap4 names a net the drawing leaves unnamed `net_NN`, numbering from zero
# on every page, so each is suffixed with its page here before the pages are
# joined, as `tools/cadrm-netlist.sh` does.
#
# MIT left no wire list of this board, so examples/reconcile.rs is run with
# `-` for the list and makes only the one pin move the board had: ECO 2 of
# cadrtv/lmtv.eco, 18 June 1980, grounding the read buffer's input for
# XDO 7 (NXBCTL F11 pin 8, drawn on SYNC PROM ENB). The 17 May 1980 drawing
# stays the source; the banner of data/SIMPLETV.netlist records the move.
#
# usage: tools/simpletv-netlist.sh
set -eu
muir=$(cd "$(dirname "$0")/.." && pwd)
mit=$muir/mit
build=$muir/vendor/soap
drw=$mit/cadrtv
[ -d "$drw/simple-tv" ] || { echo "no cadrtv drawings in $mit" >&2; exit 1; }
mkdir -p "$build"
cc -O2 -w -o "$build/soap4" "$muir/tools/soap4/soap4.c" "$muir/tools/soap4/unpack4.c"

# lmtv.stf's 29 pages carried forward, plus rampwr; in the order lmtv.stf
# lists them, TTL and MECL apart because they take different libraries.
ttl_pages="eclcap ncapa ncapb ncapc ncapd nrama nramb nramc nramd
           nraadr nrabuf ramcas nracol ramreg nrashf nsyadr nsyclk
           nxbctl nsyram nsyreg tvma ntvinc xbadr xbdata nxbus rampwr"
ecl_pages="necclk necsip eclvid"

emit() {
    library=$1
    shift
    for p in "$@"; do
        page=$(echo "$p" | tr '[:lower:]' '[:upper:]')
        "$build/soap4" -e "$drw/$library.drw" -o netlist -x cadr "$drw/simple-tv/$p.drw" > "$build/page.raw" || {
            echo "cannot read $p.drw" >&2
            exit 1
        }
        sed "s/^\(p[0-9]*=net_[0-9]*\)\$/\1@$page/" "$build/page.raw"
    done
}

{
    printf '#\n# generated by tools/simpletv-netlist.sh, using ams/cadr4 soap4\n'
    printf '# and the body libraries the drawings name, cadrtv/bod2.drw and\n'
    printf '# cadrtv/eclbod.drw\n#\n\n'
    emit bod2 $ttl_pages
    emit eclbod $ecl_pages
} > "$build/SIMPLETV.raw.netlist"
(cd "$muir" && cargo run --release --quiet --example reconcile -- \
    "$build/SIMPLETV.raw.netlist" - 0) \
    > "$muir/data/SIMPLETV.netlist"
echo "wrote data/SIMPLETV.netlist: \
$(grep -c '^page ' "$muir/data/SIMPLETV.netlist") pages, \
$(grep -c '^part ' "$muir/data/SIMPLETV.netlist") parts"
